spring.application.name=secureauth

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:secureauth_db}
spring.datasource.username=${DB_USERNAME:secureauth_admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true